Material Design 3
lneugebauer/nextcloud-cookbook pull request #100
Opened 2024-10-05 00:11 UTC by SunsetBandit

Implementation of Material Design 3. I updated every single screen. Also added a check/uncheck function to the recipe steps numbers as suggested in a TODO. Everything seems to work and i tested it both with dark and light theme.

2024-10-06 15:00 UTC, lneugebauer requested changes
First of all, thank you so much for your work!

There are a couple of things that I would like the see changed.

Once the technical side looks fine I'll go through all screens again to check for consistency of shapes and colors.

2024-10-06 15:00 UTC, lneugebauer commented on app/build.gradle
> +    implementation "com.google.accompanist:accompanist-systemuicontroller:0.36.0"
The system ui controller is deprecated and should no longer be used. Please remove it and change the implmentation.

https://google.github.io/accompanist/systemuicontroller/

2024-10-06 15:00 UTC, lneugebauer commented on app/build.gradle
> +    implementation 'androidx.activity:activity-ktx:1.9.2'
Is the activity dependency actually required? If its used, it can stay. Else please remove it.

2024-10-06 15:00 UTC, lneugebauer commented on app/build.gradle
>      implementation 'androidx.compose.material:material'
The material 2 dependency should be removed.

2024-10-06 15:00 UTC, lneugebauer commented on app/build.gradle
> +    implementation 'androidx.compose.material:material-icons-extended:1.7.3'
Please remove the versions. Dependency versions are set by the compose platform implementation.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/error/NotFoundScreen.kt
> +    }
The not found screen should use the AbstractErrorScreen so all errors look similar.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/ui/theme/Theme.kt
> +                    }
`DarkColorPalette` and `LightColorPalette` should be used to fall back to app colors.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/ui/theme/Theme.kt
> +    androidx.compose.material3.MaterialTheme(
Please import `MaterialTheme`

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/ui/theme/Theme.kt
> +            else -> {
The app currently crashes when using a device running Android 11 or lower

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/ui/theme/Theme.kt
> +        colorScheme = colorScheme as ColorScheme,
This can fail. Probably part of the reason the app currently doesn't start on devices running Android 11 or lower.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/home/HomeScreen.kt
> +private fun SingleItemPreview() {
Please add the top bar preview back again.
The SingleItem preview isn't too useful as it can't display images.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> -            } else {
The back button shouldn't be visible if no category is selected.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/res/values/strings.xml
> +    <string name="common_delete">Delete</string>
The string isn't used anywhere.

2024-10-06 15:00 UTC, lneugebauer commented on app/build.gradle
There is a material 3 version for about libs dependency.

https://github.com/mikepenz/AboutLibraries?tab=readme-ov-file#ui-module

---

The chiptextfield dependency has a material 3 version, too.

https://github.com/dokar3/ChipTextField?tab=readme-ov-file#usage

---

Same for the settings library. Don't worry to much about it, since I want to refactor the settings screen anyways.

https://github.com/alorma/Compose-Settings/tree/1.0.3?tab=readme-ov-file#install

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                shape = RoundedCornerShape(16.dp),
There are predefined shapes like `MaterialTheme.shapes.medium`.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                elevation = FloatingActionButtonDefaults.elevation(8.dp),
There is a default elevation on the fab. No reason to add it explicitly.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                containerColor = MaterialTheme.colorScheme.primary,
No reason to add the color. Its already the default.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +            ),
There is no reason to specify these colors as they seem to be the default.

2024-10-06 15:00 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
I haven't had the time to go through every ui component and check the colors and shape. Lets take the fab and top bar of the recipe detail screen as an example for all standard ui components like cards, buttons, chips and so on. Colors, elevations and shapes shouldn't be set if the default values are already fine.

I hope this already helps. I can go through the changes in the next couple if days if you want some more guidance.

2024-10-06 21:31 UTC, SunsetBandit commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
I should have changed everything requested, now it works perfectly even in android <=11 (tested on virtual device), but there are a couple of problems:

- FABs on newer versions are less rounded (and in my opinion uglier) than in older versions
- Theres a big gap between the status bar and the top bar

I can't seem to find a solution to these problems.
Also, the color of the status bar doesn't match the color of the top bar in the home screen. A solution would be to use the default color for the top bar like in the other pages, but i think it would be nice to have the primary color on the home screen.

If you have other changes just ask and I'll go through them when i can!

2024-10-06 21:33 UTC, SunsetBandit commented
I should have changed everything requested, now it works perfectly even in android <=11 (tested on virtual device), but there are a couple of problems:

- FABs on newer versions are less rounded (and in my opinion uglier) than in older versions
- There is a big gap between the status bar and the top bar

I can't seem to find a solution to these problems.
Also, the color of the status bar doesn't match the color of the top bar in the home screen. A solution would be to use the default color for the top bar like in the other pages, but i think it would be nice to have the primary color on the home screen.

If you have other changes just ask and I'll go through them when i can!

2024-10-06 23:48 UTC, SunsetBandit commented
The last thing that uses the old material library is the login ModalBottomSheet, i tried to change it directly but it's a bit different in the new version. Maybe you could take a look especially if you have to change the logic or structure.

2024-10-16 20:16 UTC, lneugebauer requested changes
Hi, here is my second review. I haven't had the time to go through the following files. I'll do that in the following days!

- LoginScreen
- CreateEditRecipeForm
- TimeTextField
- RecipeDetailScreen
- RecipeListScreen

Thanks again for the work!

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/category/presentation/list/CategoryListScreen.kt
> +                                ),
Please remove the custom style. The default looks good to me.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/category/presentation/list/CategoryListScreen.kt
> +            ),
Please remove the colors.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/MainActivity.kt
> +        enableEdgeToEdge()
Please remove the edge to edge mode. There is some more work involved to have this done correctly and I don't want to mix this up with the M3 migration. I'll create separate issue for this.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/BottomBar.kt
> +            containerColor = MaterialTheme.colorScheme.background,
Please remove the `containerColor`.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/BottomBar.kt
> +                        ),
Please remove the colors. The defaults work quite well.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/DefaultButton.kt
> +            contentColor = MaterialTheme.colorScheme.onPrimary,
Please remove the explicit `containerColor` and `contentColor` parameters, as they are already the default.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/DefaultOutlinedTextField.kt
> +            unfocusedIndicatorColor = Color.Transparent,
Please remove the colors. Calling `TextFieldDefaults.colors()` should be enough.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/Loader.kt
> +        ) // Material 3 CircularProgressIndicator
Please remove the color and strokeWidth, as they are already the defaults. Please also remove the comment.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/error/NotFoundScreen.kt
> +    ) {
Please remove the surface from the not found screen. Instead add a `Scaffold` to the abstract error screen. The `Scaffold` itself uses the `Surface` itself but respects window insets.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/error/AbstractErrorScreen.kt
> +            color = MaterialTheme.colorScheme.onBackground,
Please import the icon and text composables.

I feel like `error` is the better tint for the icon.

Please also add the small gap between the icon and text back in. Either via a padding or the `Gap` composable.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/download/DownloadRecipeScreen.kt
> +                    color = MaterialTheme.colorScheme.onSurface,
Please remove the color.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/download/DownloadRecipeScreen.kt
> +            ),
Please remove the colors.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/home/HomeScreen.kt
> +            )
Please use the `MediumTopAppBar` composable instead and remove the explicit text style.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/home/HomeScreen.kt
> +            ),
Please remove the icon tint and TopAppBar colors.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/home/HomeScreen.kt
> +            ),
Please remove the colors.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/home/HomeScreen.kt
> +        SingleItem("Lorem ipsum", "https://placehold.co/600x400?text=Hello+World") { }
Please revert the change to be the preview for the `TopAppBar` composable again.
If you need a preview for the `SingleItem` composable, please add another preview function.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/settings/presentation/libraries/LibrariesScreen.kt
> +        LibrariesContainer()
Please remove the "SuppressLint" from this file and add the scaffold padding parameter to the `LibrariesContainer` modifier.

```kotlin
Scaffold() { innerPadding ->
    LibrariesContainer(modifier = Modifier.padding(innerPadding))
}
```

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/settings/presentation/libraries/LibrariesScreen.kt
> +        contentColor = MaterialTheme.colorScheme.onSurface,
Please remove the TopAppBar and Scaffold colors.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/settings/presentation/settings/SettingsScreen.kt
Please remove all the additional colors that have been added by this PR.

2024-10-16 20:16 UTC, lneugebauer commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowLightStatusBar">true</item>
Please use `background_dark` for the status bar color and remove the `windowLightStatusBar` option.

2024-10-16 20:16 UTC, lneugebauer commented on app/build.gradle
> +    implementation "com.google.accompanist:accompanist-systemuicontroller:0.36.0"
Please remove the dependency.

2024-10-17 17:06 UTC, SunsetBandit commented
I want to apologize for the colors added: i'm quite new to android developing and it's my first contribution to a public project on GitHub. I want to thank you for this learning opportunity!

2024-10-17 18:35 UTC, lneugebauer commented
> I want to apologize for the colors added: i'm quite new to android developing and it's my first contribution to a public project on GitHub. I want to thank you for this learning opportunity!

Don't worry. I'm happy if you can learn something :)

2024-10-19 12:14 UTC, lneugebauer requested changes
Some final changes.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +                shape = MaterialTheme.shapes.medium,
Please remove the shape. There is currently a bug which results in a FAB with sharp corners. I'll fix it and once your branch is merged with main it will look good.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +                                shape = MaterialTheme.shapes.medium,
Please remove colors and shape.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                shape = MaterialTheme.shapes.medium,
Please remove the shape

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                shape = MaterialTheme.shapes.medium,
Please remove border, colors and shape.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +            AssistChip(
Please change it to be a Chip composable again.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +                            },
Please remove the label color.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +                            Text(text = recipePreview.name, style = MaterialTheme.typography.titleMedium)
Please remove the text style

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +                                style = MaterialTheme.typography.bodySmall,
Please remove the text style

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +            ),
Please remove the colors

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> +        },
It looks like this isn't a nullable parameter anymore. This can probably be simplified by doing the following:

```
navigationIcon = {
    if (categoryName != null) {
        IconButton ...
    }
},
```

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> -                    modifier = Modifier.alpha(ContentAlpha.medium),
Please add the alpha modifier again.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/list/RecipeListScreen.kt
> -                        modifier = Modifier.alpha(ContentAlpha.medium),
Please add the alpha modifier again.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/components/TimeTextField.kt
> +            unfocusedIndicatorColor = MaterialTheme.colorScheme.onSurface,
Please import TextFieldColors and simply use defaults `TextFieldDefaults.colors()`

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/DefaultOutlinedTextField.kt
> +        TextFieldDefaults.colors(
Please use `OutlinedTextFieldDefaults.colors()`

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/components/CreateEditRecipeForm.kt
> +                    unfocusedIndicatorColor = MaterialTheme.colorScheme.onSurface,
Please use `OutlinedTextFieldDefaults.colors()`

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/components/CreateEditRecipeForm.kt
> +            ),
Please remove colors

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/components/CreateEditRecipeForm.kt
> +                                    disabledLabelColor = MaterialTheme.colorScheme.onSurface,
Please use `SuggestionChip` and remove `border` and `colors`.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/components/CreateEditRecipeForm.kt
> +                                disabledLabelColor = MaterialTheme.colorScheme.onSurface,
Please use `SuggestionChip` and remove `border` and `colors`.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/core/presentation/components/DefaultTextButton.kt
Please remove `colors` from the TextButton.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +                color = MaterialTheme.colorScheme.onSurface,
Please remove the `color`.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +
Duplicated. Please remove it.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +@OptIn(ExperimentalMaterial3Api::class)
Not required anymore. Please remove it.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +                ),
Please remove `colors`.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +            ),
Please remove `colors`.

2024-10-19 12:14 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/auth/presentation/login/LoginScreen.kt
> +            ),
Please remove `colors`.

2024-10-19 12:15 UTC, lneugebauer commented
> The last thing that uses the old material library is the login ModalBottomSheet, i tried to change it directly but it's a bit different in the new version. Maybe you could take a look especially if you have to change the logic or structure.

Please leave the ModalBottomSheet as is. I'll work on it after its merged.

2024-10-20 15:28 UTC, SunsetBandit commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +            AssistChip(
There is no basic Chip in Material 3. The [migration guide](https://developer.android.com/develop/ui/compose/designsystems/material2-material3#components-and) from M2 to M3 states that i need to choose between AssistChip and SuggestionChip. Let me know what you see fit.

2024-10-20 17:27 UTC, lneugebauer commented on app/src/main/java/de/lukasneugebauer/nextcloudcookbook/recipe/presentation/detail/RecipeDetailScreen.kt
> +            AssistChip(
You are right. Then leave it as it is.

2024-10-26 10:02 UTC, lneugebauer approved these changes

2024-10-26 15:51 UTC, SunsetBandit commented
I'm having a bit of a dffucult time understanding how to resolve these conflicts, especially the CreateEditRecipeForm.kt. What would the best course of action be?

2024-10-26 15:55 UTC, merged